[package]
name = "tts"
version = "0.1.0"
authors = ["Vlad Verestiuc <verestiuc.vlad@gmail.com>"]

[dependencies]
rusoto_polly = { git = "https://github.com/rusoto/rusoto" } 
rusoto_core = { git = "https://github.com/rusoto/rusoto" } 
dbus-macros = "0.2.0"
dbus = "0.6.1"
isatty = "0.1"
alto = "3.0.1"
lewton = "0.8.0"
byteorder = "1.2.1"
punkt = "1.0.4"
quick-xml = "0.11.0"
clipboard = "0.4.4"
md5 = "0.3.7"
